# Generated by Django 4.2.24 on 2025-09-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='host_duration',
            field=models.CharField(choices=[('1_month', '1 month'), ('3_months', '3 months'), ('6_months', '6 months'), ('12_months', '12 months')], default='1_month', help_text='مدة الاستضافة للخدمة', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
