# Generated by Django 4.2.24 on 2025-10-01 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0003_project_delete_tool_rename_name_service_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
