# Generated by Django 4.2.24 on 2025-10-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0004_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
