# Generated by Django 4.2.24 on 2025-10-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0006_remove_service_price_service_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='industry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
