# Generated by Django 4.2.24 on 2025-10-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0007_order_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
